### ISSUE TITLE
question about deploying a new network

### ISSUE THREAD

**Issue by nkaramolegos** [Akachain/akc-admin-go#1]
Hello, nice work. 

I would like to use your work to deploy my network but I am not sure if fulfills all my needs. Therefore, I have some questions and I will be glad if you are available to answer them. Specifically, I would like first to create M orgs with 2 peers each one. Also, I need one more org as orderer org with maybe 3 or 4 nodes. All these M+1 orgs will be part of all the channels.  A new channel will be added after request (using the REST api) and all these orgs have to join the channel with a new chaincode (again using the appropriate endpoint of your REST api). Finally, I would like to update the chaincode of the channels after a specific request. Can I do that using your implementation? Note that I would like to extend the network (add new channel, add the orgs to the new channel, update chaincode of channel) on the fly, without affecting the operations of the other channels and the organizations.

Finally, for the transactions related communication with the network I will use one SDK gateway client which will have multiple IDs
Thus this client application can have access to channelA with ID1 and channelB with ID2, but this will be implemented independently.

**Comment by eledra89** [comment]
@nkaramolegos what platform are you working on. Native Kubernetes, Amazon EKS or Azure ?

**Comment by nkaramolegos** [comment]
Native kubernetes. For testing I am using kind

**Comment by eledra89** [comment]
Hello, @nkaramolegos, we will email you to clarify a bit more. Our document is kind of ... pretty bad in general as normally only we use it. But we are very happy if you are looking into this matter as well.

**Comment by nkaramolegos** [comment]
I am looking forward
